### ISSUE TITLE
Update Get function snippets

### ISSUE THREAD

**Issue by jwillinghalpern** [jwillinghalpern/filemaker-vscode-bundle#1]
- get1, get2 etc... are not intuitive, find a better way.
- Perhaps we can scope some constants to only work in the Get () parentheses

**Comment by rivetopia** [comment]
Here is an updated file with the get's spelled out
[filemaker.json GET updates.zip](https://github.com/jwillinghalpern/filemaker-vscode-bundle/files/2897037/filemaker.json.GET.updates.zip)

**Comment by rivetopia** [comment]
Here is an updated json file with the Get's spelled out.
[filemaker.json GET updates.zip](https://github.com/jwillinghalpern/filemaker-vscode-bundle/files/2897048/filemaker.json.GET.updates.zip)

**Comment by jwillinghalpern** [comment]
Great I’ll test these out.

**Comment by rivetopia** [comment]
update : I removed the spaces
[filemaker.json GETS (noSpace).zip](https://github.com/jwillinghalpern/filemaker-vscode-bundle/files/2897232/filemaker.json.GETS.noSpace.zip)

**Comment by jwillinghalpern** [comment]
Hey, great work. I think avoiding spaces is probably smart.

I think it might be clearer if the Get() expansions had parentheses to match Filemaker's documentation. The main reason is that there are functions that start with the word "Get" that are not a regular Get(_flag_) function. E.g. GetAsCss() and GetAsURLEncoded().

What do you think we did it like:
```
	"get(FileName)": {
	  "prefix": "get",
	  "body": "Get ( FileName )",
	  "description": "FileName",
	  "scope": "source.filemaker"
	},
```

**Comment by rivetopia** [comment]
I like the idea and seems to work just as well.  Give it a go.  [filemaker with parenthisis v5.zip](https://github.com/jwillinghalpern/filemaker-vscode-bundle/files/2898477/filemaker.with.parenthisis.v5.zip)

**Comment by rivetopia** [comment]
GetLayoutObjectAttribute need fixing : I tried a few options ; 'goa' works well
  [filemaker.json GetLayoutObjectAttribute abriv v6.zip](https://github.com/jwillinghalpern/filemaker-vscode-bundle/files/2898492/filemaker.json.GetLayoutObjectAttribute.abriv.v6.zip)

**Comment by jwillinghalpern** [comment]
Looks good I updated the repo with a couple other small edits. Credit in the changelog.

**Comment by jwillinghalpern** [comment]
changes copied to main branch

**Comment by jwillinghalpern** [comment]
> GetLayoutObjectAttribute needed fixing : I tried a few options ; 'goa' works well
> [filemaker.json GetLayoutObjectAttribute abriv_v6.zip](https://github.com/jwillinghalpern/filemaker-vscode-bundle/files/2898497/filemaker.json.GetLayoutObjectAttribute.abriv_v6.zip)

Perhaps it would be easier to track these changes if you forked the project and sent a pull request?
