### ISSUE TITLE
Incorporate text formatting/transformation functions

### ISSUE THREAD

**Issue by jwillinghalpern** [jwillinghalpern/filemaker-vscode-bundle#5]
as seen in the original bundle: https://github.com/DonovanChan/Filemaker.tmbundle

Tidy script:
https://github.com/DonovanChan/Filemaker.tmbundle/blob/master/Support/lib/tidy.pl

**Comment by jwillinghalpern** [comment]
also review: https://code.visualstudio.com/blogs/2016/11/15/formatters-best-practices

**Comment by chebfarid** [comment]
Hi Joshua,
didn't find any other place on GitHub to thank you for this work but really wanted to do so!
Great job and a real life saver if you have to work with complex calculations!
Such a shame that FMP after 30 years continues to offer such an awful scripting/calculating interface.
Thanks again
Farid, Milan/Italy

**Comment by jwillinghalpern** [comment]
@chebfarid 
Thanks for your kind words! I'm grateful that FM has introduced some improvements, but I agree, it's much nicer to work on complex calculations in a code editor.

I'm obliged to mention again the work of Matt Petrowsky and Donovan Chandler whose work I based the project on. They deserve a lot of the thanks.

👍 
Josh
