### ISSUE TITLE
How to use

### ISSUE THREAD

**Issue by skygamer125** [jwillinghalpern/filemaker-vscode-bundle#9]
How can someone use this extension? what file do I need to open it with to be able to use it and get the syntax and such?

**Comment by jwillinghalpern** [comment]
If you haven't already, install it in visual studio code in the extensions menu. Alternatively you can install from here:
https://marketplace.visualstudio.com/items?itemName=jwillinghalpern.filemaker-vscode

Once installed you can select FileMaker from the vscode language selector and it will highlight and provide snippets.

The file extensions .fmfn and .calc should use FileMaker highlighting automatically.
